# Generated by Django 3.0.7 on 2020-06-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_default_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Admin')], default=0),
        ),
    ]
