# Generated by Django 3.0.4 on 2020-06-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uniq_id',
            field=models.TextField(null=True),
        ),
    ]
